Changes in CI File

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -48,22 +48,22 @@ jobs:
         npm install
         npm test
 
-    - name: Debug SonarQube connectivity
-      run: |
-        curl -v ${{ secrets.SONAR_URL }}/api/server/version || echo "Failed to reach SonarQube"
-        curl -u ${{ secrets.SONAR_TOKEN}}: ${{ secrets.SONAR_URL }}/api/projects/search || echo "Token auth failed"
-        # ping -c 4 https://1403-86-98-147-96.ngrok-free.app || echo "Ping failed"
+    # - name: Debug SonarQube connectivity
+    #   run: |
+    #     curl -v ${{ secrets.SONAR_URL }}/api/server/version || echo "Failed to reach SonarQube"
+    #     curl -u ${{ secrets.SONAR_TOKEN}}: ${{ secrets.SONAR_URL }}/api/projects/search || echo "Token auth failed"
+    #     # ping -c 4 https://1403-86-98-147-96.ngrok-free.app || echo "Ping failed"
 
-    - name: SonarQube Scan with Retry
-      uses: nick-fields/retry@v3
-      with:
-        timeout_seconds: 600
-        max_attempts: 3
-        command: |
-          docker run --rm -e SONAR_HOST_URL=${{ secrets.SONAR_URL }} -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
-          -v $(pwd):/usr/src sonarsource/sonar-scanner-cli:latest \
-          -Dsonar.projectBaseDir=. -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300 -Dsonar.verbose=true \
-          -Dsonar.scanner.force-deprecated-java-version-check=false
+    # - name: SonarQube Scan with Retry
+    #   uses: nick-fields/retry@v3
+    #   with:
+    #     timeout_seconds: 600
+    #     max_attempts: 3
+    #     command: |
+    #       docker run --rm -e SONAR_HOST_URL=${{ secrets.SONAR_URL }} -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
+    #       -v $(pwd):/usr/src sonarsource/sonar-scanner-cli:latest \
+    #       -Dsonar.projectBaseDir=. -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300 -Dsonar.verbose=true \
+    #       -Dsonar.scanner.force-deprecated-java-version-check=false
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
@@ -90,11 +90,13 @@ jobs:
 
     - name: Debug Trivy ignore file
       run: |
+        pwd
         ls -lh nextjs-app/.trivyignore || echo "nextjs-app/.trivyignore not found"
         cat nextjs-app/.trivyignore || echo "Failed to read nextjs-app/.trivyignore"
+        file nextjs-app/.trivyignore || echo "Failed to inspect nextjs-app/.trivyignore"
 
     - name: Scan nextjs-app image with Trivy
-      uses: aquasecurity/trivy-action@master
+      uses: aquasecurity/trivy-action@0.24.0
       with:
         image-ref: yazilansari/nextjs-app:${{ github.sha }}
         format: table
